version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: mobdev
      POSTGRES_DB: produtodb
    ports:
      - "54321:54321"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data: